### ISSUE TITLE
Drag'n'drop of elements inside the sidebar

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#15]
Elements and containers inside the sidebar should be draggable into containers (to move element to another container)

**Comment by tomalec** [comment]
Added also in https://github.com/Polyjuice/Launcher/issues/59

**Comment by miyconst** [comment]
`juicy-draggable` has been improved to support drag & drop functionality, not only drag around.

The demo is available here: http://juicy.github.io/juicy-tile-editor/examples/juicy-draggable.html

In the sidebar tree the folder icon is the drop zone. The tree items may be dragged and dropped to groups.

Also fixed _Move to group button_. Previously it moved `selectedItems[1]` to `selectedItems[0].container`, now it checks whether `selectedItems[0]` is a container and if so then moves `selectedItems[1]` to it, not to it's container.

I still don't like the UI of sidebar. Even simple _Product details_ page requires lots of groups with nesting to make it look nice. The sidebar is too small in width for that number of nesting levels, the font size is also small, and the items are not very distinguished from each other.

The most easy way would be to increase sidebar width, font size, gap between items, on hover highlight entire item instead of `span` with name, but the main problem is amount of items inside. If we do all of these points, then vertical and horizontal scrolls will be much bigger.

@warpech, `juicy-draggable` is quite a big and standalone element, should I move it to its own repository?

**Comment by miyconst** [comment]
Closing the issue, the drag & drop feature works and the sidebar was reworked.
