### ISSUE TITLE
Make tree window float, and be draggable

### ISSUE THREAD

**Issue by tomalec** [Juicy/juicy-tile-editor#36]
Duplicate of https://github.com/Polyjuice/Launcher/issues/58

**Comment by miyconst** [comment]
The sidebar (tree window) is now draggable and floatable.

There are eight positions: `left`, `left-top`, `top`, `right-top`, `right`, `right-bottom`, `bottom`, `left-bottom`, the sidebar sticks to a position automatically if it was dropped closer than 80px to window's edge; otherwise it stays wherever user drops it.

`juicy-draggable` wraps this script: https://github.com/gtramontina/draggable.js with some extra features.

**Comment by warpech** [comment]
@miyconst can this be closed?

**Comment by miyconst** [comment]
Yes.
