### ISSUE TITLE
Renaming of items in the sidebar tree

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#51]
Currently, the top bar displays:
- readonly item id
- editable input for item display name

The sidebar tree displays:
- readonly item id (as display name in case the display name is empty, and as `title` attribute)
- readonly display name

Let's make that more user friendly by following a well established pattern:
1. remove the item id and the display name from the top bar
2. make the display name editable in the sidebar by double-clicking on the label

![screenshot 2015-05-12 10 16 53](https://cloud.githubusercontent.com/assets/566463/7582716/a6f041d0-f890-11e4-90eb-e09b3c803285.png)

**Comment by miyconst** [comment]
How to get the item id then? What would be the width of the text box? Some of the names are very long.

**Comment by warpech** [comment]
We have 3 "names" for an item:
- `item.id` (currently displayed as title of the tree element and in top bar)
- `item.itemName` - _explicit display name_
- `toDisplayName(item, branch)` - _implicit display name_, displayed in case there is no explicit display names

The width of the edit field should be the all available space in the sidebar (use flexbox for that? or span with [contenteditable](http://stackoverflow.com/questions/26970999/contenteditable-inside-polymer-element)?)

The edit field should show _implicit display name_ as the placeholder text.

Does it make sense now?

**Comment by miyconst** [comment]
Actually no.

We need id for the tiles, lets say I need to do some manual changes in my json setup. For this, I have to find proper id of needed item. It is very simple right now: click the item, select the id, copy it, search in json.

If the section [id: name] is removed from the top bar, and only edit field left, then how do I select & copy actual tile id?

Double click to edit could be good if we rid off the _three names_ and use only one. Also the input[text] or span[editable] should not exceed width of the sidebar and this can be done only after vertical scroll is removed. Otherwise very long names will cause blink after double click, because width of text and input won't be the same.

**Comment by warpech** [comment]
We agreed on a meeting (@miyconst, @tomalec, me) and we decided that `itemName` may be should be generated once by `juicy-tile-editor` if it does not exist in setup. Setup will be in the dirty state until it is saved.

From now on, we have only 2 names: `id` (internal) and `itemName` (display name in the tree).

**Comment by miyconst** [comment]
Done.

The `itemName` can now be edited by duble click on an item.
