### ISSUE TITLE
Dragging to a group changes relative dimension to absolute

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-tile-editor#61]
Reproducible running Launcher 2.0.0-pre14, Chatter 0.0.0-pre2 and Images 2.0.0-pre8.
1. Go to a room in Chatter app with default styles.
2. Open layout editor.
3. Drag `<so-juicy-filedrop>`  (width: 100%) to group `root_1` (width: 85%)
4. Error happens: the dimensions of `root_1` are changed to pixel value (1262 in my case)

Screenshots

Desired:

![screenshot 2015-06-03 09 39 20](https://cloud.githubusercontent.com/assets/566463/7954967/a413d7d8-09d4-11e5-8e05-9a8022679374.png)

Actual:

![screenshot 2015-06-03 09 39 49](https://cloud.githubusercontent.com/assets/566463/7954961/a0dedfe0-09d4-11e5-94bb-0d2978dcfc50.png)

**Comment by miyconst** [comment]
Current add to group method recalculates dimensions for the parent group to make sure that every element has enough space inside.

This can be disabled, but then layout designer should care about group size by himself.

I think it is okay. If I have a group with 20% width and I drag to there some buttons, then it means that I want all of them fit in 20% of screen width.

**Comment by miyconst** [comment]
@tomalec what do you think?

**Comment by tomalec** [comment]
I do agree that if you have big container and you would like to put some items inside it should not shrink.

The only cases to resize the container I find are:
1. When you have a group X wide and Y tall, oriented `"rightDown"`(horizontal layers, LTR), full of items, then you try to put an element X by Z, I would expect group to become X by Y+Z.
2. When you have group 200 by 200, with two elements 200 by 100, then you try to move huge picture (1000 by 1000) inside, then I would expect the group to grow to 1000 by 1200, so the picture will fit the group instead of get placed in `0,0` and overlay the other tiles, as it does not fit in there at all.

So both cases applies to the absolute size (given in `Number`), however for relative dimensions (given in `"%"`), there might be a problem if you move an item with `width: "50%"` to a group oriented `"downRight"` (vertical layers top-to-bottom), as then we may end up with `\infty`

**Comment by warpech** [comment]
Discussed today that this should be fixed. The values entered in % should be kept in % after moving to a group

**Comment by warpech** [comment]
Let's put a high priority on this after we are done with migrating all our stuff to Polymer 1.1

**Comment by miyconst** [comment]
Okay, I assign it on me, will ask @tomalec in case of any trouble.

**Comment by miyconst** [comment]
Just removed a couple of code lines: https://github.com/Juicy/juicy-tile-editor/commit/4ee97218623a86f26ee59fe8363dd9288ff5c743
