### ISSUE TITLE
The input string should reflect the real value

### ISSUE THREAD

**Issue by Starcounter-Jack** [Juicy/juicy-tile-editor#95]
We should have the width and height fields contain the CSS value with a clear unit.

100%
50px
200fr

**Comment by tomalec** [comment]
Right now we have switch between `%` and `px`. (https://github.com/Juicy/juicy-tile-editor/issues/124)
We decided not to expose fr unit per element, until we expose also a feature to specify a number of all fractions available.  (https://github.com/Starcounter/RebelsLounge/issues/21)

Otherwise `fr` makes no sense, as then all elements will be backed into same line.
